# Parameters
IMG_SIZE = 224
CHANNELS = 3
INPUT_SHAPE = (IMG_SIZE, IMG_SIZE, CHANNELS)

DATA_DIR = '../../dataset'
TRAIN_DIR = f'{DATA_DIR}/train'
TEST_DIR = f'{DATA_DIR}/test'

EPOCHS = 100
BATCH_SIZE = 32
LEARNING_RATE = 0.001
STEPS_MULTIPLIER = 1
